# Generated by Django 5.2.7 on 2025-11-04 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-creada_en'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AddField(
            model_name='tarea',
            name='actualizada_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['usuario', '-creada_en'], name='tareas_tare_usuario_851174_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['usuario', 'completada'], name='tareas_tare_usuario_69083c_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['usuario', 'prioridad'], name='tareas_tare_usuario_ea2c36_idx'),
        ),
    ]
