# Generated by Django 5.2.7 on 2025-11-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_etiqueta_tarea_etiquetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='hora_vencimiento',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
