# Generated by Django 5.2.7 on 2025-11-06 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_tarea_hora_vencimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['orden', '-creada_en'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.RemoveIndex(
            model_name='tarea',
            name='tareas_tare_usuario_851174_idx',
        ),
        migrations.AddField(
            model_name='tarea',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden personalizado del usuario'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['usuario', 'orden', '-creada_en'], name='tareas_tare_usuario_c3238a_idx'),
        ),
    ]
