# Generated by Django 5.2.7 on 2025-11-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_alter_tarea_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Tarea visible públicamente'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
