# Generated by Django 5.2.7 on 2025-11-06 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_tarea_is_public_tarea_share_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('completada', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='tareas.tarea')),
            ],
            options={
                'verbose_name': 'Subtarea',
                'verbose_name_plural': 'Subtareas',
                'ordering': ['orden', 'creada_en'],
            },
        ),
    ]
